language: php

php:
    - "7.2"

before_script:
    - cp .env.travis .env
    - composer self-update
    - composer install --no-interaction

script:
    - ./vendor/bin/phpcs --standard=psr2 app/
    - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
