version: '3'
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: '172.30.0.0/16'
services:
    nginx:
        build:
            context: ./docker/nginx
        depends_on:
            - php
        ports:
            - 80:80
            - 443:443
        expose:
            - "9001"
            - "80"
            - "443"
        extra_hosts:
          - dockerhost:172.30.0.1
        volumes:
            - ./:/src

    php:
        build:
            context: ./docker/php
        environment:
            DB_HOST: mysql
        volumes:
            - ./:/src

    mysql:
        image: mysql:5.7
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=pawn
            - MYSQL_PASSWORD=kingsgambit
            - MYSQL_DATABASE=gambit
        ports:
            - 3306:3306

    logspout:
        image: amouat/logsput-logstash
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 8000:80: